#!/bin/sh
#
# @author Jun Futagawa

GITHUB_SSH="git@github.com"

REPOSITORY_NAME="$1"
BRANCHES="$2"

if [[ ! -z "${GITHUB_ORGS}" ]]; then
    GITHUB_USER="${GITHUB_ORGS}"
fi

if [[ -z "${GITHUB_USER}" ]]; then
    echo "GITHUB_USER or GITHUB_ORGS need to be set."
    echo "ex) export GITHUB_USER=username"
    echo "ex) export GITHUB_ORGS=orgname"
    exit 1
fi

if [[ -z ${REPOSITORY_NAME} ]]; then
    echo "$0 REPOSITORY_NAME [BRANCHES]"
    echo "ex) $0 projectname"
    echo "ex) $0 projectname project-1.x,project-2.x"
    exit 1
fi

if [[ -z ${BRANCHES} ]]; then
    BRANCHES=$(git branch -a | egrep -v "/tags/|@|master$|remotes/trunk" | sed 's/.*remotes\///g')
fi

IS_ALREADY=$(grep '\[remote "origin"\]' .git/config | wc -l)
if [[ ${IS_ALREADY} -eq 0 ]]; then
    REMOTE_NAME="origin"
else 
    REMOTE_NAME="${GITHUB_USER}"
fi

IS_ALREADY=$(grep "\[remote \"${REMOTE_NAME}\"\]" .git/config | wc -l)
if [[ ${IS_ALREADY} -eq 0 ]]; then
    echo "[push remote add ${REMOTE_NAME}]"
    git remote add "${REMOTE_NAME}" "${GITHUB_SSH}:${GITHUB_USER}/${REPOSITORY_NAME}.git"
fi

echo "[push branches to ${REMOTE_NAME}]"
IFS=',
'
for i in ${BRANCHES}
do
    BRANCH="${i}"
    git checkout -b ${BRANCH} remotes/${BRANCH}
    git push ${REMOTE_NAME} ${BRANCH}
done
