#!/bin/sh
#
# @author Jun Futagawa

REPOSITORY_NAME="$1"

if [[ -z "${GITHUB_USER}" ]]; then
    echo "GITHUB_USER need to be set."
    echo "ex) export GITHUB_USER=username"
    exit 1
fi

if [[ -z "${GITHUB_PASS}" ]]; then
    echo "GITHUB_PASS need to be set."
    echo "ex) export GITHUB_PASS=pasword"
    exit 1
fi

if [[ -z "${REPOSITORY_NAME}" ]]; then
    echo $0 REPOSITORY_NAME
    exit 1
fi

GITHUB_ROOT=""
if [[ -z "${GITHUB_ORGS}" ]]; then
    GITHUB_ROOT="repos/${GITHUB_USER}"
else
    GITHUB_ROOT="repos/${GITHUB_ORGS}"
fi

echo "[delete a repository on ${GITHUB_ROOT}]"

for REPOSITORY in ${@}; do
    echo "[delete ${REPOSITORY} repository]"
    curl -s -u "${GITHUB_USER}:${GITHUB_PASS}" "https://api.github.com/${GITHUB_ROOT}/${REPOSITORY}" -X DELETE
done
