#!/bin/sh
#
# @author Jun Futagawa

TEAM_NAME="$1"

if [[ -z "${GITHUB_USER}" ]]; then
    echo "GITHUB_USER need to be set."
    echo "ex) export GITHUB_USER=username"
    exit 1
fi

if [[ -z "${GITHUB_PASS}" ]]; then
    echo "GITHUB_PASS need to be set."
    echo "ex) export GITHUB_PASS=pasword"
    exit 1
fi

if [[ -z "${TEAM_NAME}" ]]; then
    echo $0 TEAM_NAME
    exit 1
fi

GITHUB_ROOT=""
if [[ -z "${GITHUB_ORGS}" ]]; then
    GITHUB_ROOT="users/${GITHUB_USER}"
else
    GITHUB_ROOT="orgs/${GITHUB_ORGS}"
fi

TEAM_ID=$(curl -u "${GITHUB_USER}:${GITHUB_PASS}" "https://api.github.com/${GITHUB_ROOT}/teams" | jq ".[] | select(.name == \"${TEAM_NAME}\").id")
if [[ ! -z "${TEAM_ID}" ]]; then
    echo "${TEAM_NAME} already exists."
    exit 1
fi

echo "[add a team: ${TEAM_NAME}]"
CREATE_JSON="{\"name\":\"${TEAM_NAME}\", \"permission\":\"admin\"}"
curl -u "${GITHUB_USER}:${GITHUB_PASS}" "https://api.github.com/${GITHUB_ROOT}/teams" -d "${CREATE_JSON}"
