#!/bin/sh
#
# @author Jun Futagawa

# remove git-svn-id
echo "remove git-svn-id"
git filter-branch --tag-name-filter cat --msg-filter 'sed -e "/git-svn-id:/d"' -f -- --all

# replace empty commit messages
echo "replace empty commit messages"
git filter-branch --tag-name-filter cat --msg-filter '
read msg
if [ -n "$msg" ] ; then
    echo "$msg"
else
    echo "<empty commit message>"
fi' -f -- --all

# [branches only] remove empty commit
#echo "remove empty commit"
#git filter-branch -f --prune-empty
