#!/bin/bash
#
# manual: git log --pretty=oneline
#
# @author Jun Futagawa

function debug() {
    if [[ ${DEBUG} ]]
    then
        echo ">>> $*"
    fi
}

IFS='
'

TAG_LIST=`cat $1`
for i in ${TAG_LIST}
do
    PARENT_SVN_COMMIT_ID=$(echo ${i} | cut -d ' ' -f 1)
    VERSION=$(echo ${i} | cut -d ' ' -f 2)
    debug ""
    debug "PARENT_SVN_COMMIT_ID: ${PARENT_SVN_COMMIT_ID}"
    debug "VERSION: ${VERSION}"

    PARENT_COMMIT=$(git log -1 --format='%H %at %s' --grep "@${PARENT_SVN_COMMIT_ID} " --all)
    if [[ ${PARENT_COMMIT} = "" ]]; then
        echo "# ${VERSION}: parent commit not found"
        debug "  ${VERSION}: parent commit not found"
        exit 1
    fi
    debug "PARENT_COMMIT: ${PARENT_COMMIT}"
    PARENT_TAG_HASH=$(echo ${PARENT_COMMIT} | cut -d ' ' -f 1)
    PARENT_COMMIT_DATE=$(echo ${PARENT_COMMIT} | cut -d ' ' -f 2)

    echo "GIT_COMMITTER_DATE='${PARENT_COMMIT_DATE}' git tag -a ${VERSION} -m '${VERSION} リリース' ${PARENT_TAG_HASH}"
done
